ritzley/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from oscar.app import application

from django.conf import settings
from django.conf.urls.static import static

from Custom_apps.cart.app import application1

urlpatterns = [
	url(r'^i18n/', include('django.conf.urls.i18n')),
	# url(r'^register/', views.UserRegistration.as_view(), name='UserRegistration'),
	# The Django admin is not officially supported; expect breakage.
	# Nonetheless, it's often useful for debugging.
	url(r'^admin/', include(admin.site.urls)),
	url(r'', include(application.urls)),

	## Custom urls in cart
	url(r'', include(application1.urls)),

	


	# ----------------Custom Urls-----------------------------------
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Custom_apps/cart/models.py
from django.db import models
import datetime

from django.contrib.auth.models import User

from Custom_apps.dashboard.models import *
from Custom_apps.dashboard.tailor.models import *
from Custom_apps.customer.models import *

class Cart(models.Model):
	# Model for cart items
	# Stores all items linked along with user

	user = models.ForeignKey(User, null=True, blank=True)
	image = models.ImageField(default="Unknown.jpg")
	name = models.CharField(max_length=100, null=True, blank=True)
	price = models.IntegerField(default=0)
	stitching_price = models.IntegerField(default=0)
	added_date = models.DateField(auto_now_add=True)

	type_of_item = models.CharField(max_length=50)	# product, stitching, custom
	type_id = models.IntegerField(default=0)		# product_id
	size_id = models.IntegerField(default=0)		# size_id

	product = models.ForeignKey(Product, null=True, blank=True)
	chosen_size = models.ForeignKey(Product_size1, null=True, blank=True)
	patterns = models.ManyToManyField(TailorPatterns, null=True, blank=True)

	category = models.ForeignKey(TailorCategory, null=True, blank=True)

	status =  models.CharField(max_length=50, null=True, blank=True)
	stitching = models.CharField(max_length=50, null=True, blank=True)

	def __unicode__(self):
		return "{0} - {1} - {2}".format(self.id, self.name, self.price)


class Transaction(models.Model):
	# Model for storing transaction from COD

	STATUS = (
		('order_processing', 'Order processing'),
		('sent_to_tailor', 'Sent to tailor'),
		('tailoring_over', 'Tailoring over'),
		('shipped_to_customer', 'Shipped to customer'),
		('delivered', 'Delivered'),
		('canceled', 'Order Canceled'),
	)

	user = models.ForeignKey(User, null=True, blank=True)
	address = models.ForeignKey(Address, null=True, blank=True)
	
	product = models.ForeignKey(Product, null=True, blank=True)
	size = models.ForeignKey(Product_size1, null=True, blank=True)
	tailor = models.ForeignKey(Tailor, null=True, blank=True)
	patterns = models.ManyToManyField(TailorPatterns, null=True, blank=True)
	category = models.ForeignKey(TailorCategory, null=True, blank=True)
	amount = models.IntegerField(default=0)

	date_of_purchase = models.DateField(auto_now_add=True)
	date_modified = models.DateField(auto_now_add=True)

	status = models.CharField(max_length=100, null=True, blank=True, choices=STATUS, default='order_processing')


	def __unicode__(self):
		return "{0} - {1}".format(self.id, str(self.date_of_purchase))

Custom_apps/dashboard/tailor/models.py
from django.db import models
# Create your models here.



# Tailor Model
class Tailor(models.Model):
	# TODO: Define fields here
	
	name = models.CharField(max_length=50, blank=False, null=False)
	description = models.TextField(blank=True, null=True)
	banner_image = models.ImageField(default="Unknown.jpg", blank=True, null=True)
	logo = models.ImageField(default="Unknown.jpg", blank=True, null=True)
	location = models.CharField(blank=True, null=True, max_length=50)
	url = models.CharField(max_length=1024, default="ritzley.com", null=False, blank=False)
	active = models.BooleanField(default=True)
	email = models.CharField(max_length = 1024,blank=True)
	# service_offered = models.ManyToManyField(TailorCategory, blank=True, null=True)
	# portfolio = models.ManyToManyField(TailorPortfolio, blank=True, null=True)
	
	def __unicode__(self):
		return "{0} - {1}".format(self.name, self.url)


class TailorPortfolio(models.Model):
	# TODO: Define fields here

	tailor = models.ForeignKey(Tailor, null=False, blank=False)
	name = models.CharField(max_length=50, blank=False, null=False)
	banner_image = models.ImageField(default="Unknown.jpg", blank=False, null=False)
	
	def __unicode__(self):
		return "{0} - {1}".format(self.name, self.tailor.name)


# Tailor Category Model
class TailorCategory(models.Model):
	# TODO: Define fields here
	
	tailor = models.ForeignKey(Tailor, null=False, blank=False)
	name = models.CharField(max_length=50, blank=False, null=False)
	image = models.ImageField(default="Unknown.jpg")
	base_price = models.IntegerField(default=0)
	# sub_category = models.ManyToManyField(TailorSubCategory)

	def __unicode__(self):
		return "{0} - {1}".format(self.name, self.tailor.name)


# Tailor Sub-Category Model
class TailorSubCategory(models.Model):
	# TODO: Define fields here
	tailor = models.ForeignKey(Tailor, null=False, blank=False)
	category = models.ForeignKey(TailorCategory, null=False, blank=False)
	name = models.CharField(max_length=50, blank=False, null=False)
	# patterns = models.ManyToManyField(TailorPatterns)

	def __unicode__(self):
		return "{0} - {1}".format(self.name, self.category.name)



# Tailor Patterns Model
class TailorPatterns(models.Model):
	# TODO: Define fields here

	tailor = models.ForeignKey(Tailor, null=False, blank=False)
	sub_category = models.ForeignKey(TailorSubCategory, null=False, blank=False)
	name = models.CharField(max_length=50, blank=False, null=False)
	image = models.ImageField(default="Unknown.jpg")
	price = models.IntegerField(default=0)

	def __unicode__(self):
		return "{0} - {1} - {2}".format(self.name, self.tailor.name, self.sub_category.name)

Custom_apps/dashboard/tailor/forms.py
from django import forms
from models import *
from Custom_apps.dashboard.tailor.models import *


class TailorForm(forms.ModelForm):

    class Meta:
        model = Tailor
        exclude = [],


class TailorPortfolioForm(forms.ModelForm):

    class Meta:
        model = TailorPortfolio
        exclude = [],


class TailorCategoryForm(forms.ModelForm):

    class Meta:
        model = TailorCategory
        exclude = [],


class TailorSubCategoryForm(forms.ModelForm):

    class Meta:
        model = TailorSubCategory
        exclude = [],


class TailorPatternsForm(forms.ModelForm):

    class Meta:
        model = TailorPatterns
        exclude = [],

Custom_apps/cart/views.py
from oscar.apps.customer.views import AccountAuthView as CoreAccountAuthView
from django.contrib.auth import logout 
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, HttpResponse, redirect
from django.views.generic import View, TemplateView, RedirectView
from django.contrib.auth.models import User
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.template import RequestContext, Context, Template
from django.contrib import auth
from django.core.context_processors import csrf 
from django.contrib.auth.forms import UserCreationForm
from Custom_apps.customer.forms import *

from django.template.loader import get_template

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

import datetime as dt
import json, string, os
import hashlib, random
import json
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
from django.core.mail import send_mail
from django.contrib.auth.hashers import *
from django.core.urlresolvers import reverse, reverse_lazy

from django.db.models import Q, Sum

from django.utils.text import slugify

from Custom_apps.customer.models import *
from models import *

from django.contrib import messages
from django.core.mail import EmailMessage

# Functions

def Mailer(subject, content, to, template_html):

	from_email = ""
	html = get_template(template_html)
	d = Context(content)
	html_content = html.render(d)

	try:
		email = EmailMessage(subject, html_content, 'support@ritzley.com', [to])
		email.content_subtype = "html"  # Main content is now text/html
		email.send()
	except Exception, e:
		pass


def addProductToBag(user, product, chosen_size):

	if product.discount > 0:
		price = product.discount_amount
	else:
		price = product.price

	name = product.name
	type_of_item = "product"
	type_id = product.id

	images = product.image.all()

	if len(images) > 0:
		image = images.first().image.name
	else:
		image = "Unknown.jpg"

	category = product.category.name
	# cat = TailorCategory.objects.get(name__icontains=category)

	# print cat
	obj = Cart(user=user, image = image, name = name, price = price, type_of_item = type_of_item, type_id = type_id, size_id=chosen_size.id, product=product, chosen_size=chosen_size, stitching=product.stitching)
	obj.save()

	return obj.id


def getMyTotal(request):

	price = 0
	if request.user.is_authenticated():
		items = Cart.objects.filter(user = request.user)
		for item in items:
			if item.type_of_item == "product":
				price += item.price

			elif item.type_of_item == "stitching":
				prod_price = item.price
				stitching_cost = item.category.base_price
				pat_tot = item.patterns.all().aggregate(Sum('price'))
				pat_price = pat_tot['price__sum']

				price += stitching_cost + prod_price + pat_price

			elif item.type_of_item == "custom":
				if item.category is not None:
					stitching_cost = item.category.base_price
					tot = item.patterns.all().aggregate(Sum('price'))
					price += stitching_cost + tot['price__sum']

	return price


def getMyCartItems(request):

	items_json = []
	if request.user.is_authenticated():
		items = Cart.objects.filter(user = request.user)
		for item in items:
			c = {}

			if item.type_of_item == "product":

				c['id'] = item.id
				c['name'] = item.name
				c['type'] = item.type_of_item
				c['image'] = item.image.name
				c['tid'] = item.product.id
				c['price'] = item.price
				c['size'] = item.chosen_size.product_size
				c['url'] = item.product.boutique.url
				c['type'] = "product"
				c['date'] = str(dt.date.today())

			elif item.type_of_item == "stitching":

				base_price = item.category.base_price
				pat_sum = item.patterns.all().aggregate(Sum('price'))
				price = base_price + pat_sum['price__sum']

				c['id'] = item.id
				c['name'] = item.name
				c['type'] = item.type_of_item
				c['image'] = item.image.name
				c['tid'] = item.product.id
				c['price'] = item.price
				c['size'] = item.chosen_size.product_size
				c['url'] = item.product.boutique.url

				c['st_name'] = item.name
				c['st_price'] = price
				c['st_image'] = item.category.tailor.logo.name
				c['st_url'] = item.category.tailor.url
				c['type'] = "stitching"
				c['date'] = str(dt.date.today())

			elif item.type_of_item == "custom":

				if item.category is not None:

					base_price = item.category.base_price
					pat_sum = item.patterns.all().aggregate(Sum('price'))
					price = base_price + pat_sum['price__sum']

					c['st_price'] = price
					c['st_image'] = item.category.tailor.logo.name
					c['st_url'] = item.category.tailor.url
				else:
					c['st_url'] = "ritzley.com"
					c['st_image'] = "Unknown.jpg"
					c['st_price'] = "(process incomplete)"


				c['id'] = item.id
				c['type'] = item.type_of_item
				# c['name'] = item.name
				# c['image'] = item.image.name
				# c['tid'] = 0
				# c['price'] = item.price
				# c['size'] = 0
				# c['url'] = "#"

				c['st_name'] = item.name
				c['type'] = "custom"
				c['date'] = str(dt.date.today() + dt.timedelta(5))
				

			items_json.append(c)

	return items_json


# Create your views here.

class CartView(TemplateView):
	
	template_name = "cart.html"

	def get(self, request, *args, **kwargs):

		context = {}

		if request.user.is_authenticated():

			context['cart'] = getMyCartItems(request)
			tot = getMyTotal(request)
			print tot
			context['total'] = tot

		else:
			return HttpResponseRedirect('/')

		return render(request, self.template_name, context)

	def post(self, request, *args, **kwargs):
		context = {}

		if request.user.is_authenticated():

			flag = 0

			items = getMyCartItems(request)
			for item in items:
				print item
				if item['type'] == "custom":
					if item['st_price'] == "(process incomplete)":
						messages.error(request, "Please complete the process to proceed or remove the items from cart!")
						flag = 1
						break

			if flag == 0:
				return HttpResponseRedirect('/check_out')
			else:
				return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))



# Add a product to the cart
class CartAddToBag(View):

	def post(self, request, **kwargs):

		context = {}
		prod_id = kwargs["product_id"]
		size = request.POST.get('size-product', '')

		print prod_id, size

		if request.user.is_authenticated():

			if size and prod_id:
				# try:
				pdt = Product.objects.get(id=prod_id)
				chosen_size = pdt.size.get(id=size)

				print pdt, chosen_size

				# raise error is out of stock
				if chosen_size.stock == 0:
					messages.error(request, "Sorry, product " + str(pdt.name) + " of size "+ str(chosen_size.product_size)  +" is out of stock!")
					return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
				else:
					user = request.user
					ret = addProductToBag(user, pdt, chosen_size)

					messages.success(self.request, pdt.name + " Added to Cart")

				# except Exception, e:
					# messages.error(request, "Product Does not Exist")

				site = request.get_host()
				url1 = "http://" + site + "/" + slugify(pdt.name) + "_" + str(pdt.id)
				print url1

			else:
				messages.error(request, "Missing args!")
		else:
			return HttpResponseRedirect("/")

		# return redirect(url1)
		return redirect(request.META.get('HTTP_REFERER', '/'))




# Add a product to the cart
class CartAddToBagAjax(View):

	def get(self, request, **kwargs):

		context = {}
		prod_id = kwargs["product_id"]
		size = request.GET.get('size-product', '')

		print prod_id, size

		if request.user.is_authenticated():

			if size and prod_id:
				# try:
				pdt = Product.objects.get(id=prod_id)
				chosen_size = pdt.size.get(id=size)

				# raise error is out of stock
				if chosen_size.stock == 0:
					out = "-1" # no stock
				else:
					user = request.user
					ret = addProductToBag(user, pdt, chosen_size)
					self.request.session['cart_id'] = ret

					out = ret

				# except Exception, e:
					# messages.error(request, "Product Does not Exist")

			else:
				out = "-2" # missing args
		else:
			out = "-3" # access denied

		return HttpResponse(out)


# Delete any item from the cart
class CartDeleteFromBagAjax(View):

	def get(self, request, *args, **kwargs):

		context = {}
		prod_id = kwargs["item_id"]

		if request.user.is_authenticated():
			if prod_id:
				try:
					obj = Cart.objects.get(id=prod_id)
					obj.delete()
				except Exception, e:
					out = "-1"

				out = "1"
			else:
				out = "-2" # missing args
		else:
			out = "-3" # access denied

		return HttpResponse(out)


class CartDeleteFromBag(TemplateView):

	template_name = "cart.html"

	def get(self, request, *args, **kwargs):

		context = {}
		prod_id = kwargs["item_id"]

		if request.user.is_authenticated():
			try:
				obj = Cart.objects.get(id=prod_id)
				obj.delete()
			except Exception, e:
				messages.error(request, "Product Does not Exist")

			messages.success(request, obj.name + " Removed from Cart")

		return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))



class CartDeleteStitchingFromBag(TemplateView):

	template_name = "cart.html"

	def get(self, request, *args, **kwargs):

		context = {}
		prod_id = kwargs["item_id"]

		if request.user.is_authenticated():
			try:
				obj = Cart.objects.get(id=prod_id)
				obj.patterns.clear()
				obj.type_of_item = "product"
				obj.save()
				# obj.delete()
			except Exception, e:
				messages.error(request, "Product Does not Exist")

			messages.success(request, obj.name + " Stitching cost Removed from Cart")

		return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))



class CartDeleteStitchingFromBagAjax(View):

	def get(self, request, *args, **kwargs):

		context = {}
		prod_id = kwargs["item_id"]

		if request.user.is_authenticated():
			if prod_id:
				try:
					obj = Cart.objects.get(id=prod_id)
					obj.patterns.clear()
					obj.type_of_item = "product"
					obj.save()
				except Exception, e:
					out = "-1"

				out = "1"
			else:

ritzley/templates/checkout.html
{% extends "base2.html" %}

{% block content %}

<!-- Start header Section-->
<section class="header-section fading-title parallax" style="background-size: 110%; background-position: 76.8292682926829% 38.4146341463415%;">
  <div class="section-shade sep-top-3x sep-bottom-2x">
    <div class="container">
      <div class="section-title upper light" style="opacity: 1; margin-bottom: 0px; margin-top: 0px;">
        <h2 class="small-space">Checkout</h2>
        <p class="lead">Confirm your order</p>
      </div>
    </div>
  </div>
</section>

<!-- End header Section-->

<section class="sep-top-md">

  <div class="container">
    <h4 class="upper">Billing details</h4>

    <div class="container">
      <div class="panel-group" id="accordion">
        <div class="panel panel-default">
          <div data-toggle="collapse" data-parent="#accordion" href="#collapseOne" class="panel-heading">
            <h4 class="panel-title">
              <a href="#">Current Billing Address</a>
            </h4>
          </div>
          <div id="collapseOne" class="panel-collapse collapse in">
            <div class="panel-body">
              <div class="col-md-12">

                {% if addresses %}
                {% if addresses|length == 0 %}
                <div class="combined">No Addresses found</div>
                {% else %}

                {% for address in addresses %}

                <div class="combined">
                  <input type="radio" class="radio" name="address_radio" value="{{ address.id }}" {% if address.last_used %} checked="checked" {% endif %} onclick='$("#id_address").val($(this).val());' />
                  <div class="single_address">

                    <div class="btn btn-default btn-circle"><a href="/delete_address/{{ address.id }}/">X</a></div>

                    <span class="id_first_name">{{ address.first_name }}</span> <span class="id_last_name">{{ address.last_name }}</span>,
                    <span class="id_address_line_1">{% if address.address_line_1 %}<br/> {{ address.address_line_1 }}{% endif %}</span>,
                    <span class="id_address_line_2">{% if address.address_line_2 %}<br/>{{ address.address_line_2 }}{% endif %}</span>,
                    <span class="id_city">{% if address.city %}<br />{{ address.city }}{% endif %}</span>,
                    <span class="id_state">{% if address.state %}{{ address.state }}{% endif %}</span>,
                    <span class="id_country">{% if address.country %}{{ address.country }}{% endif %}</span>-
                    <span class="id_postcode">{% if address.postcode %}{{ address.postcode }}{% endif %}</span>
                    <span class="id_mobile_number"><br />{% if address.mobile_number %}{{ address.mobile_number }}{% endif %}</span>
                  </div>
                </div>

                {% endfor %}

                {% endif %}

                {% else %}
                <div class="combined">No Addresses found</div>
                {% endif %}

              </div>

            </div>
          </div>
        </div>

        <div class="panel panel-default">
          <div data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" id="id_add_new" class="panel-heading">
            <h4 class="panel-title">
              <a href="#">Add/Edit Address</a>
            </h4>
          </div>
          <div id="collapseTwo" class="panel-collapse collapse">
            <div class="panel-body">
              <form action="/addnewaddress/" class="form" method="POST" id="add_address_form" name="sub_form">{% csrf_token %}

                <input type="hidden" name="a_id" id="id_a_id" value="{{ current.id }}">

                <div class="col-sm-3 form-group">
                  <label class="sr-only">First Name</label>
                  <input type="text" placeholder="First Name" id="id_edit_first_name" name="first_name" required="true" aria-required="true" class="form-control input-lg" value="{{ current.first_name }}">
                </div>
                <div class="col-sm-3 form-group">
                  <label class="sr-only">Last Name</label>
                  <input type="text" placeholder="Last Name" id="id_edit_last_name" name="last_name" required="true" aria-required="true" class="form-control input-lg" value="{{ current.last_name }}">
                </div>

                <!--
                <div class="col-sm-3 form-group">
                  <label class="sr-only">Email</label>
                  <input type="text" placeholder="Email" id="id_edit_" name="email" required="true" aria-required="true" class="form-control input-lg" value="{{ current.email }}">
                </div>
              -->

              <div class="col-sm-3 form-group">
                <label class="sr-only">Mobile Number</label>
                <input type="number" placeholder="Mobile Number" id="id_edit_mobile_number" name="mobile_number" required="true" aria-required="true" class="form-control input-lg" value="{{ current.mobile_number }}">
              </div>

              <div class="col-sm-6 form-group">
                <label class="sr-only">Address Line 1</label>
                <input type="text" placeholder="Address Line 1" id="id_edit_address_line_1" name="address_line_1" required="true" aria-required="true" class="form-control input-lg" value="{{ current.address_line_1 }}">
              </div>

              <div class="col-sm-6 form-group">
                <label class="sr-only">Address Line 2</label>
                <input type="text" placeholder="Address Line 2" id="id_edit_address_line_2" name="address_line_2" required="true" aria-required="true" class="form-control input-lg" value="{{ current.address_line_2 }}">
              </div>

              <div class="col-sm-3 form-group">
                <label class="sr-only">Town / City</label>
                <input type="text" placeholder="Town / City" id="id_edit_city" name="city" required="true" aria-required="true" class="form-control input-lg" value="{{ current.city }}">
              </div>

              <div class="col-sm-3 form-group">
                <label class="sr-only">Postcode</label>
                <input type="number" placeholder="Postcode / Zip" id="id_edit_postcode" name="postcode" required="true" aria-required="true" class="form-control input-lg" value="{{ current.postcode }}">
              </div>

              <div class="col-sm-3 form-group">
                <label class="sr-only">State</label>
                <input type="text" placeholder="State" id="id_edit_state" name="state" required="true" aria-required="true" class="form-control input-lg" value="{{ current.state }}">
              </div>

              <div class="col-sm-3 form-group">
                <label class="sr-only">Country</label>
                <input type="text" placeholder="Country" id="id_edit_country" name="country" required="true" aria-required="true" class="form-control input-lg" value="{{ current.country }}">
              </div>

              <div class="col-lg-12 text-right">
                <button type="button" onclick="ClearForm(this.form)" class="btn btn-primary">Reset</button>
                <button type="submit" class="btn btn-primary">Save Address</button>
              </div>

            </form>
          </div>
        </div>
      </div>

    </div>
  </div>



  <div class="row">
    <div class="col-md-12">
      <div class="sep-top-lg">
        <h4 class="upper">Your Order</h4>
        <div class="sep-top-sm">
          <table class="table table-bordered table-condensed table-responsive">

            <tr>
              <th scope="col" class="dark upper">
                Cart Items
              </th>
              <th scope="col" class="dark upper">
                Total
              </th>
            </tr>

            <tbody>

              {% if cart %}
              {% if cart|length == 0 %}
              <tr><td colspan="2">No Items in your Cart</td></tr>
              {% else %}

              {% for item in cart %}

              {% if item.type|slugify == "product" or item.type|slugify == "stitching" %}

              <tr>
                <td>{{ item.name }} ({{ item.size }})</td>
                <td>
                  <h5 class="upper">₹&nbsp;{{ item.price }}</h5>
                </td>
              </tr>

              {% endif %}

              {% if item.patterns|length > 0 %}

              {% if item.type|slugify == "stitching" %}

              <tr>
                <td>{{ item.st_name }} Stitching Cost</td>
                <td>
                  <h5 class="upper">₹&nbsp;{{ item.st_price }}</h5>
                </td>
              </tr>

              {% endif %}

              {% if item.type|slugify == "custom" %}

              <tr>
                <td>{{ item.st_name }} Stitching Cost</td>
                <td>
                  <h5 class="upper">
                    {% if item.st_price|slugify == "process-incomplete" %}
                    <a style="font-size:16px;" class="btn btn-primary btn-xs" href='/cart/continue/{{ item.id }}/'>Complete Process</a>
                    {% else %}
                    ₹&nbsp;{{ item.st_price }}
                    {% endif %}
                  </h5>
                </td>
              </tr>

              {% endif %}
              {% endif %}
              {% endfor %}

              <tr>
                <td>Shipping and Handling</td>
                <td>
                  <h5>Free</h5>
                </td>
              </tr>

              <tr class="evidence">
                <td class="upper">
                  <h5>Order Total</h5>
                </td>
                <td class="upper">
                  <h5>₹&nbsp;{{ total }}</h5>
                </td>
              </tr>

              {% endif %}
              {% else %}
              <tr><td colspan="2">No Items in your Cart</td></tr>
              {% endif %}

            </tbody>
          </table>
        </div>
      </div>
    </div>

    <div class="col-md-12 sep-top-md sep-bottom-2x text-right">
      {% if cart %}
      {% if cart|length != 0 %}
      <form action="" method="POST" class="form" id="checkout_global_form" name="main_form">{% csrf_token %}
        <input type="hidden" id="id_address" name="address_radio" value="{{ first }}">
        <button type="submit" class="btn btn-primary btn-lg">Place order</button>
      </form>
      {% endif %}
      {% endif %}
    </div>

  </div>
</div>

</section>


{% endblock content %}




{% block scripts %}
<script type="text/javascript">

  $(document).ready(function() {
    $(".page").addClass('cart');

    {% if addresses %}
    {% if addresses|length == 0 %}
    $("#id_add_new").trigger('click');
    {% endif %}
    {% else %}
    $("#id_add_new").trigger('click');
    {% endif %}

    $(".radio").click(function(event) {

      var id = $(this).val();

      var text = $(this).parent().find('.id_first_name').text();

      $("#id_edit_first_name").val($(this).parent().find('.id_first_name').text());
      $("#id_edit_last_name").val($(this).parent().find('.id_last_name').text());
      $("#id_edit_mobile_number").val($(this).parent().find('.id_mobile_number').text());
      $("#id_edit_address_line_1").val($(this).parent().find('.id_address_line_1').text());
      $("#id_edit_address_line_2").val($(this).parent().find('.id_address_line_2').text());
      $("#id_edit_city").val($(this).parent().find('.id_city').text());
      $("#id_edit_country").val($(this).parent().find('.id_country').text());
      $("#id_edit_state").val($(this).parent().find('.id_state').text());
      $("#id_edit_postcode").val($(this).parent().find('.id_postcode').text());
      $("#id_a_id").val(id);

      // $("#id_add_new").trigger('click');
    });

  });

function ClearForm(form){

  var frm_elements = form.elements;
    // var frm_elements = $("#add_address_form").elements;

    for (i = 0; i < frm_elements.length; i++)
    {
      field_type = frm_elements[i].type.toLowerCase();
      switch (field_type)
      {
        case "text":
        case "password":
        case "textarea":
        case "hidden":
        if (frm_elements[i].name != "csrfmiddlewaretoken"){
          frm_elements[i].value = "";
        }
        break;
        case "radio":
        case "checkbox":
        if (frm_elements[i].checked)
        {
          frm_elements[i].checked = false;
        }
        break;
        case "select-one":
        case "select-multi":
        frm_elements[i].selectedIndex = -1;
        break;
        default:
        break;
      }
    }

  }

</script>

{% endblock scripts %}

{% block styles %}

<style>
  .panel-heading {
    background-color:#CF1E75 !important;
    color:white !important;
  }

  .panel-heading a:link a:visited, a:active {
    color:white !important;
  }

  .panel-heading a:hover, a:focus {
    color:#cccccc !important;
  }

  .single_address{
    background-color: #eeeeee;
    color: black;
    border-radius: 5px;
    padding: 10px;
    max-width: 450px;
    float: left;
    margin-left: 10px;
    min-width: 400px;
  }

  .radio{
    float: left;
  }

  .combined{
    margin: 10px;
    padding: 10px;
    clear: both;
  }

  .btn-circle {
    width: 30px;
    height: 30px;
    text-align: center;
    padding: 6px 0;
    font-size: 12px;
    line-height: 1.42;
    border-radius: 15px;
    color: white;
    float: right;
  }

</style>

{% endblock styles %}

ritzley/templates/register_success.html
{% extends "base.html" %}

{% block content %}

  <h2>You Have Registered!</h2>

{% endblock %}