ritzley/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from oscar.app import application

from django.conf import settings
from django.conf.urls.static import static

from Custom_apps.cart.app import application1

urlpatterns = [
	url(r'^i18n/', include('django.conf.urls.i18n')),
	# url(r'^register/', views.UserRegistration.as_view(), name='UserRegistration'),
	# The Django admin is not officially supported; expect breakage.
	# Nonetheless, it's often useful for debugging.
	url(r'^admin/', include(admin.site.urls)),
	url(r'', include(application.urls)),

	## Custom urls in cart
	url(r'', include(application1.urls)),

	


	# ----------------Custom Urls-----------------------------------
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Custom_apps/dashboard/models.py
from django.db import models
# from oscar.apps.dashboard.models import *
from django.contrib.auth.models import User
from Custom_apps.dashboard.tailor.models import Tailor, TailorCategory

import datetime


class Faq(models.Model):

	description = models.TextField()

	class Meta:
		verbose_name = "Faq"
		verbose_name_plural = "Faqs"

	def __unicode__(self):
		return self.description



class Templatepage(models.Model):
	# TODO: Define fields here
	
	name = models.CharField(max_length=50)

	def __unicode__(self):
		return self.name


class Color(models.Model):

	name = models.CharField(blank=False, null=False,max_length=50)

	def __unicode__(self):
		return self.name


"""
If more stiching category needed to be entered, then use below model for stiching
"""
# class Stiching(models.Model):

# 	title = models.CharField(blank=False, null=False,max_length=50)

# 	def __unicode__(self):
# 		return self.title


class Boutique(models.Model):
	# TODO: Define fields here
	
	name = models.CharField(max_length=50, blank=False, null=False)
	description = models.TextField(blank=True, null=True)
	faq = models.TextField(blank=True, null=True)
	refund_policy = models.TextField(blank=True, null=True)
	terms_conditions = models.TextField(blank=True, null=True)
	header_image = models.ImageField(default="Unknown.jpg",blank=True, null=True)
	logo = models.ImageField(default="Unknown.jpg", blank=True, null=True)
	placeholder_1 = models.ImageField(default="Unknown.jpg", blank=True, null=True, verbose_name='Placeholder 1')
	placeholder_2 = models.ImageField(default="Unknown.jpg", blank=True, null=True, verbose_name='Placeholder 2')
	location = models.CharField(blank=False, null=False, max_length=50)
	featured = models.BooleanField(default=False)
	template = models.ForeignKey(Templatepage, blank=False, null=False, default=False)
	url = models.CharField(max_length=1024, default="ritzley.com", null=False, blank=False)
	fb_url = models.CharField(max_length=1024, default="facebook.com", null=True, blank=True)
	tailor = models.ForeignKey(Tailor, blank=True, null=True)
	active = models.BooleanField(default=True)
	email = models.CharField(max_length = 1024,blank=True)
	
	def __unicode__(self):
		return self.name


# Category for products
class Category(models.Model):

	name = models.CharField(blank=False, null=False, max_length=50)
	def __unicode__(self):
		return self.name


# Product size for product. This is inserted in seperate table because each size has its on stock
class Product_size1(models.Model):
	
	product_size = models.CharField(blank=False, null=False, max_length=50)
	stock = models.IntegerField(blank=False, null=False, default=0)

	def __unicode__(self):
		return "{0} - {1} - {2}".format(self.id, self.product_size, self.stock)

# Images for products are used
class Product_image1(models.Model):

	image = models.ImageField(default="Unknown.jpg")

	def __unicode__(self):
		return self.image.name


# Product model for inserting products 
class Product(models.Model):


	STITCHED = 'Stitched'
	HALF_STITCHED = 'Half-Stitched'
	FULL_STITCHED = 'Non-Stitched'

	STITCHING = (
		(STITCHED, 'Stitched'),
		(HALF_STITCHED, 'Half-Stitched'),
		(FULL_STITCHED, 'Non-Stitched'),
	)

	boutique = models.ForeignKey(Boutique, blank=False, null=False, related_name="boutique", default=True)
	category = models.ForeignKey(Category, blank=False, null=False, default=True)
	name = models.CharField(blank=False, null=False, max_length=50,default="")
	# stock = models.IntegerField(default=0)
	price = models.IntegerField(blank=False, null=False, max_length=50,default=0)
	description = models.TextField(blank=True, null=True, max_length=1000)
	tags = models.CharField(blank=True, null=True, max_length=1000)
	discount = models.IntegerField(default = 0, blank=True, null=True)
	discount_amount = models.IntegerField(default = 0, blank=True, null=True)
	color = models.ForeignKey(Color, blank=False, null=False, default=True)
	# stiching = models.ForeignKey(Stiching, blank=False, null=False, default=True)
	stitching = models.CharField(max_length=50, choices=STITCHING, default=STITCHED)
	added_date = models.DateTimeField('date added', auto_now=True, auto_now_add=True, default=datetime.date.today())
	featured = models.BooleanField(default=False)

	image = models.ManyToManyField(Product_image1, null=True, blank=True)
	size = models.ManyToManyField(Product_size1, null=True, blank=True)

	def __unicode__(self):
		return "{0} - {1} - {2}".format(self.id, self.name, self.stitching)


"""Model for capturing user's favourite boutiques"""
class Boutique_favourite(models.Model):

	user = models.ForeignKey(User, blank=False, null=False, default=True)
	boutique = models.ForeignKey(Boutique, blank=False, null=False, default=True)

	def __unicode__(self):
		return self.boutique.name









	

Custom_apps/dashboard/tailor/models.py
from django.db import models
# Create your models here.



# Tailor Model
class Tailor(models.Model):
	# TODO: Define fields here
	
	name = models.CharField(max_length=50, blank=False, null=False)
	description = models.TextField(blank=True, null=True)
	banner_image = models.ImageField(default="Unknown.jpg", blank=True, null=True)
	logo = models.ImageField(default="Unknown.jpg", blank=True, null=True)
	location = models.CharField(blank=True, null=True, max_length=50)
	url = models.CharField(max_length=1024, default="ritzley.com", null=False, blank=False)
	active = models.BooleanField(default=True)
	email = models.CharField(max_length = 1024,blank=True)
	# service_offered = models.ManyToManyField(TailorCategory, blank=True, null=True)
	# portfolio = models.ManyToManyField(TailorPortfolio, blank=True, null=True)
	
	def __unicode__(self):
		return "{0} - {1}".format(self.name, self.url)


class TailorPortfolio(models.Model):
	# TODO: Define fields here

	tailor = models.ForeignKey(Tailor, null=False, blank=False)
	name = models.CharField(max_length=50, blank=False, null=False)
	banner_image = models.ImageField(default="Unknown.jpg", blank=False, null=False)
	
	def __unicode__(self):
		return "{0} - {1}".format(self.name, self.tailor.name)


# Tailor Category Model
class TailorCategory(models.Model):
	# TODO: Define fields here
	
	tailor = models.ForeignKey(Tailor, null=False, blank=False)
	name = models.CharField(max_length=50, blank=False, null=False)
	image = models.ImageField(default="Unknown.jpg")
	base_price = models.IntegerField(default=0)
	# sub_category = models.ManyToManyField(TailorSubCategory)

	def __unicode__(self):
		return "{0} - {1}".format(self.name, self.tailor.name)


# Tailor Sub-Category Model
class TailorSubCategory(models.Model):
	# TODO: Define fields here
	tailor = models.ForeignKey(Tailor, null=False, blank=False)
	category = models.ForeignKey(TailorCategory, null=False, blank=False)
	name = models.CharField(max_length=50, blank=False, null=False)
	# patterns = models.ManyToManyField(TailorPatterns)

	def __unicode__(self):
		return "{0} - {1}".format(self.name, self.category.name)



# Tailor Patterns Model
class TailorPatterns(models.Model):
	# TODO: Define fields here

	tailor = models.ForeignKey(Tailor, null=False, blank=False)
	sub_category = models.ForeignKey(TailorSubCategory, null=False, blank=False)
	name = models.CharField(max_length=50, blank=False, null=False)
	image = models.ImageField(default="Unknown.jpg")
	price = models.IntegerField(default=0)

	def __unicode__(self):
		return "{0} - {1} - {2}".format(self.name, self.tailor.name, self.sub_category.name)

Custom_apps/dashboard/forms.py
from django import forms
from models import *
from Custom_apps.dashboard.models import *

# Create your forms here

class BoutiqueForm(forms.ModelForm):

    class Meta:
        model = Boutique
        exclude = [],


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ['category', 'name', 'price', 'description', 'tags', 'discount','featured', 'image', 'boutique', 'stitching', ]
        exclude = ['boutique', 'discount_amount', 'added_date,', 'size', 'image', ]


class Product_image_form(forms.ModelForm):

    class Meta:
        model = Product_image1
        exclude = [],



class Product_size_form(forms.ModelForm):

    class Meta:
        model = Product_size1
        exclude = [],


class DocumentForm(forms.Form):
    image = forms.ImageField()

Custom_apps/dashboard/tailor/forms.py
from django import forms
from models import *
from Custom_apps.dashboard.tailor.models import *


class TailorForm(forms.ModelForm):

    class Meta:
        model = Tailor
        exclude = [],


class TailorPortfolioForm(forms.ModelForm):

    class Meta:
        model = TailorPortfolio
        exclude = [],


class TailorCategoryForm(forms.ModelForm):

    class Meta:
        model = TailorCategory
        exclude = [],


class TailorSubCategoryForm(forms.ModelForm):

    class Meta:
        model = TailorSubCategory
        exclude = [],


class TailorPatternsForm(forms.ModelForm):

    class Meta:
        model = TailorPatterns
        exclude = [],

Custom_apps/dashboard/users/forms.py
from django import forms
from django.contrib.auth.models import User


# Create your forms here

class UserForm(forms.Form):
	# TODO: Define form fields here

	first_name = forms.CharField()
	last_name = forms.CharField()
	email = forms.EmailField()
	password = forms.CharField(widget=forms.PasswordInput)


class UserModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password']
        # widgets = {
        #     'password': forms.PasswordInput(),
        # }

Custom_apps/dashboard/users/views.py
from oscar.apps.dashboard.users.views import IndexView as CoreIndexView
from oscar.apps.dashboard.users.views import UserDetailView as CoreUserDetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib import messages
from django.views.generic import View, TemplateView
import string, os
from django.core.mail import send_mail
from django.shortcuts import redirect
from .forms import UserForm, UserModelForm
from django.views.generic.detail import DetailView
from django.core.mail import EmailMessage
from django.template import RequestContext, Context, Template
from django.template.loader import get_template


# -------------------------------------------General Functions---------------------------------
def Mailer(subject, content, to, template_html):

	from_email = ""
	html = get_template(template_html)
	d = Context(content)
	html_content = html.render(d)

	try:
		email = EmailMessage(subject, html_content, 'support@ritzley.com', [to])
		email.content_subtype = "html"  # Main content is now text/html
		email.send()
	except Exception, e:
		pass


# Write your views here
"""This view subclasses the original user IndexView"""
class IndexView(CoreIndexView):
	"""docstring for IndexView"""

	template_name = 'dashboard/users/index.html'

	def get_context_data(self, **kwargs):
		context = super(IndexView, self).get_context_data(**kwargs)
		return context


"""This view is for Adding users"""
class AddUserView(TemplateView):
	"""docstring for IndexView"""

	template_name = 'dashboard/users/add_user.html'
	form_class = UserForm

	def get_context_data(self, **kwargs):
	    context = super(AddUserView, self).get_context_data(**kwargs)
	    context['form'] = self.form_class
	    return context

	def post(self, request):
		
		first_name = request.POST.get('first_name','')
		last_name = request.POST.get('last_name','')
		email = request.POST.get('email','')
		password = request.POST.get('password','')

		user = User.objects.create_user(email, email, password)
		user.first_name = first_name
		user.last_name = last_name
		user.is_active = True
		user.is_staff = True
		user.is_superuser = True
		user.save()
		messages.success(request, "Added admin successfully")


		return redirect(reverse_lazy('dashboard:users-index'))


"""This view is for rendering details about specific user"""
class UserDetailView(CoreUserDetailView):
	"""docstring for UserDetailView"""
	
	template_name = "dashboard/users/detail.html"


"""This view Edits the user details"""
class UpdateUserView(TemplateView):
	"""docstring for EditUserView"""
	
	template_name = "dashboard/users/update.html"

	def get_context_data(self, **kwargs):

	    context = super(UpdateUserView, self).get_context_data(**kwargs)
	    user_id = kwargs['pk']
	    user_obj = User.objects.get(id=user_id)
	    context['form'] = UserModelForm(instance=user_obj)
	    return context

	def post(self,request, **kwargs):
		
		user_id = kwargs['pk']

		first_name = request.POST.get('first_name','')
		last_name = request.POST.get('last_name','')
		email = request.POST.get('email','')
		password = request.POST.get('password','')

		user_obj = User.objects.get(id=user_id)

		if user_obj.first_name != first_name:
			user_obj.first_name = first_name

		if user_obj.last_name != last_name:
			user_obj.last_name = last_name

		if user_obj.email != email:
			user_obj.email = email

		if user_obj.password != password:
			user_obj.set_password(password)

		user_obj.save()

		return redirect(reverse_lazy('dashboard:users-index'))


"""This view Edits the user details"""
class DeleteUserView(DeleteView):
	"""docstring for EditUserView"""
	
	model = User
	template_name = "dashboard/users/delete.html"
	success_url = reverse_lazy('dashboard:users-index')


"""This view is for reseting password of users from dashboard via admin"""
class PasswordResetView(View):
	"""docstring for PasswordReset"""
	
	def post(self, request):

		email = request.POST.get('email', '')


		if email != '':

			try:
				u1 = User.objects.get(email = email)
			except Exception, e:
				messages.error(request, "User Does not Exist")
				c['error'] = "User Does not Exist"
				return render(request, 'iforgotthis.html', c)

			if u1:
				cid = u1.id
				print "user exists!"

				hash1 = generate_random_string(32, '0123456789ABCDEF')
				url = request.META['HTTP_HOST']

				link = "http://" + url + "/accounts/hasher/" + str(cid) +"/"+ str(hash1) +"/"
				print link

				content = {}
				content['user'] = u1
				content['url'] = link

				to = email
				subject = 'Account Password Reset'
				template_html = "reset_mail.html"

				Mailer(subject, content, to, template_html)

				messages.success(request, "Password Reset Mail sent to " + email)

		
		return redirect(reverse_lazy('dashboard:users-index'))
	


# -------------------------------------Functions----------------------------------------------------
"""Function for generating random string"""
def generate_random_string(length, stringset=string.ascii_letters+string.digits):
	'''
	Returns a string with `length` characters chosen from `stringset`
	>>> len(generate_random_string(20) == 20
	'''

	str = ''.join([stringset[i%len(stringset)] for i in [ord(x) for x in os.urandom(length)]])

	return str

ritzley/templates/dashboard/tailor/category_edit.html
{% extends 'dashboard/index.html' %}
{% load i18n %}
{% load staticfiles %}

{% block headertext %}
    <span>{% trans "Edit Tailor Category" %}</span>
{% endblock %}

{% block dashboard_content %}

<form action="" method="post" enctype="multipart/form-data" >
	{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
{% endblock %}

ritzley/templates/dashboard/tailor/pattern_delete.html
{% extends 'dashboard/index.html' %}
{% load i18n %}
{% load staticfiles %}

{% block headertext %}
    <span>{{pattern.name}}</span> <span>{% trans "Tailor Patterns" %}</span>
{% endblock %}

{% block dashboard_content %}

<form action="" method="post">
{% csrf_token %}
    <p>Are you sure you want to delete "{{ pattern }}"?</p>
    <input type="submit" value="Confirm" />
</form>

{% endblock %}

ritzley/templates/dashboard/tailor/pattern_edit.html
{% extends 'dashboard/index.html' %}
{% load i18n %}
{% load staticfiles %}

{% block headertext %}
    <span>{% trans "Edit Tailor Pattern" %}</span>
{% endblock %}

{% block dashboard_content %}

<form action="" method="post" enctype="multipart/form-data" >
	{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
{% endblock %}

ritzley/templates/dashboard/tailor/portfolio_add.html
{% extends 'dashboard/index.html' %}
{% load i18n %}
{% load staticfiles %}

{% block headertext %}
	{% trans "Tailor Portfolio" %}
{% endblock %}

{% block dashboard_content %}
	<form action="" method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{form.as_p}}
	<input type="submit" value="Submit" class="btn btn-primary">
	</form>
	<a href="/dashboard/"><input type="button" value="Home" class="btn btn-primary"></a>

{% endblock %}

ritzley/templates/dashboard/tailor/portfolio_edit.html
{% extends 'dashboard/index.html' %}
{% load i18n %}
{% load staticfiles %}

{% block headertext %}
    <span>{% trans "Edit Tailor Portfolio" %}</span>
{% endblock %}

{% block dashboard_content %}

<form action="" method="post" enctype="multipart/form-data" >
	{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
{% endblock %}

ritzley/templates/dashboard/tailor/subcategory_delete.html
{% extends 'dashboard/index.html' %}
{% load i18n %}
{% load staticfiles %}

{% block headertext %}
    <span>{{category.name}}</span> <span>{% trans "Category" %}</span>
{% endblock %}

{% block dashboard_content %}

<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ category }}"?</p>
    <input type="submit" value="Confirm" />
    <input  type="button" value="Cancel" onclick="window.history.back()">
    
</form>

{% endblock %}

ritzley/templates/dashboard/tailor/subcategory_edit.html
{% extends 'dashboard/index.html' %}
{% load i18n %}
{% load staticfiles %}

{% block headertext %}
<span>{% trans "Edit Tailor Sub Category" %}</span>
{% endblock %}

{% block dashboard_content %}

<form action="" method="post" enctype="multipart/form-data" >
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Update" />
</form>
{% endblock %}

ritzley/templates/dashboard/tailor/tailor_add_params.html
{% extends 'dashboard/index.html' %}
{% load i18n %}
{% load staticfiles %}
{% load thumbnail %}
{% block headertext %}
{% trans "Tailor" %}
{% endblock %}

{% block dashboard_content %}

<div class="page-content" style="padding-right:45px; margin-left:10px;">
	<div class="content-block">
		<a href="/dashboard/" class="btn btn-primary">Home</a>
	</div>
</div>

<div class="page-content" style="clear:both; padding-right:45px; margin-left:10px;">
	<div class="table-header">Add Tailor</div>
	<div class="content-block">
		<div>
			<form action="" method="POST" enctype="multipart/form-data" id="tailor_form">{% csrf_token %}

				<p><label for="id_banner_image">Banner image:</label>
					{% thumbnail object.banner_image "x200" crop="center" as image %}
					<img src="{{image.url}}" alt="{{tailor.name}}" data-description="">
					{% endthumbnail %}
				</p>

				<p><label for="id_logo">Logo:</label>
					{% thumbnail object.logo "x200" crop="center" as image %}
					<img src="{{image.url}}" alt="{{tailor.name}}" data-description="">
					{% endthumbnail %}
				</p>

				<p><label for="id_name">Name:</label> <input id="id_name" maxlength="50" name="name" type="text" value="{{ object.name }}" readonly="true"></p>
				<p><label for="id_description">Description:</label><textarea cols="40" id="id_description" name="description" rows="10" readonly="true">{{ object.description }}</textarea></p>


				<p><label for="id_location">Location:</label> <input id="id_location" maxlength="50" name="location" type="text" value="{{ object.location }}" readonly="true"></p>
				<p><label for="id_url">Url:</label> <input id="id_url" maxlength="1024" name="url" type="text" value="{{ object.url }}" readonly="true"></p>
				<p><label for="id_active">Active:</label> <input {% if object.active %} checked="checked" {% endif %} id="id_active" name="active" type="checkbox" disabled="true"></p>


				<div style="clear:both;"></div>

				{% if services|length > 0 %}
				<div class="page-content" style="min-width:48%; padding:10px;">
					<div class="table-header">Category List</div>
					<div class="content-block">
						<table class="table table-responsive table-hover">
							<thead>
								<tr>
									<th>Category Name</th>
									<th>Base Price</th>
									<th>Edit</th>
									<th>Delete</th>
								</tr>
							</thead>

							<tbody>
								{% for item in services %}
								<tr>
									<td><a href="{{ item.id }}/">{{ item.name }}</a></td>
									<td>{{ item.base_price }}</td>
									<td><a href="/dashboard/tailor/category/edit/{{ item.id }}/?tailor_id={{ object.id }}">Edit</a></td>
									<td><a href="/dashboard/tailor/category/delete/{{ item.id }}/?tailor_id={{ object.id }}">Delete</a></td>
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
				{% endif %}



				{% if portfolios|length > 0 %}
				<div class="page-content" style="min-width:48%; padding:10px;">
					<div class="table-header">Portfolio List</div>
					<div class="content-block">
						<table class="table table-responsive table-hover">
							<thead>
								<tr>
									<th>Portfolio Name</th>
									<th>Edit</th>
									<th>Delete</th>
								</tr>
							</thead>
							<tbody>
								{% for item in portfolios %}
								<tr>
									<td>{{ item.name }}</td>
									<td><a href="/dashboard/tailor/portfolio/edit/{{ item.id }}/?tailor_id={{ object.id }}">Edit</a></td>
									<td><a href="/dashboard/tailor/portfolio/delete/{{ item.id }}/?tailor_id={{ object.id }}">Delete</a></td>
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
				{% endif %}

			</form>

			<div style="clear:both;"></div>

		</div>
	</div>
</div>

<br />
<br />
<br />

<div class="page-content" style="float:left; min-width:48%; padding:10px;">
	<div class="table-header">Add Portfolio</div>
	<div class="content-block">
		<div>
			<label>Upload {{ form_portfolio.visible_fields.1.label }}</label>
			<form action="/dashboard/tailor/portfolio/add/image/" class="dropzone" id="my-awesome-dropzone1" style="min-height: 200px; max-width: 500px;" method="POST">
				{% csrf_token %}
				<div class="fallback">
					<input name="file" type="file" accept="image/*"/>
				</div>
			</form>
		</div>

		<form action="" method="POST" enctype="multipart/form-data" id="tailor_portfolio_form">{% csrf_token %}
			{# {{form_portfolio.as_p}} #}
			{{ form_portfolio.visible_fields.1.label }}<br />{{ form_portfolio.visible_fields.1 }}<br />
			<br />
			<br />
			<br />
			<br />
			<input type="submit" value="Submit" class="btn btn-primary">
		</form>
	</div>
</div>


<div class="page-content" style="float:left; min-width:48%; padding:10px;">
	<div class="table-header">Add Category</div>
	<div class="content-block">
		<div>
			<label>Upload {{ form_category.visible_fields.1.label }}</label>
			<form action="/dashboard/tailor/category/add/image/" class="dropzone" id="my-awesome-dropzone2" style="min-height: 200px; max-width: 500px;" method="POST">
				{% csrf_token %}
				<div class="fallback">
					<input name="file" type="file" accept="image/*"/>
				</div>
			</form>
		</div>

		<form action="" method="POST" enctype="multipart/form-data" id="tailor_category_form">
			{% csrf_token %}
			{# {{form_category.as_p}} #}
			{{ form_category.visible_fields.1.label }}<br />{{ form_category.visible_fields.1 }}<br />
			{{ form_category.visible_fields.3.label }}<br />{{ form_category.visible_fields.3 }}<br />

			<br />
			<input type="submit" value="Submit" class="btn btn-primary">
		</form>
	</div>
</div>


<div style="clear:both;"></div>


{% endblock %}



{% block extrastyles %}

<!-- DROPZONE -->
<link rel="stylesheet" type="text/css" href={% static "js/dropzone/dropzone.min.css" %} />
<!--
<link rel="stylesheet" type="text/css" href="//select2.github.io/dist/css/select2.min.css" />
-->

{% endblock extrastyles %}



{% block extrascripts %}

<!-- DROPZONE -->
<script type="text/javascript" src={% static "js/dropzone/dropzone.min.js" %}></script>
<!--
<script type="text/javascript" src="//select2.github.io/dist/js/select2.full.js"></script>
-->


<script type="text/javascript">

	$(document).ready(function() {

		Dropzone.autoDiscover = false;
		var myDropzone1 = new Dropzone("#my-awesome-dropzone1", {
			url: "/dashboard/tailor/portfolio/add/image/",
			maxFileSize: 5,
			acceptedFiles: "image/*",
			uploadMultiple: false,
			// addRemoveLinks: true,
		});
		var myDropzone2 = new Dropzone("#my-awesome-dropzone2", {
			url: "/dashboard/tailor/category/add/image/",
			maxFileSize: 5,
			acceptedFiles: "image/*",
			uploadMultiple: false,
			// addRemoveLinks: true,
		});

		$("#tailor_category_form").submit(function(event) {
			var name = $("#id_form_cat-name").val();
			var base_price = $("#id_form_cat-base_price").val();

			$.ajax({
				url: '/dashboard/tailor/category/add/ajax/'+name+'/'+base_price+'/{{ object.id }}/',
				type: 'GET',
				dataType: 'text',
				success: function(data, textStatus, xhr) {
					// $("#id_form_subcat-category").append('<option value="'+data+'">'+name+'</option>');
					// $("#id_form_pat-category").append('<option value="'+data+'" selected>'+name+'</option>');

					// $("#id_form_cat-name").val('');
					// myDropzone2.removeAllFiles(true);

					if(data!="0"){
						alert('Category added!');
						window.location.reload();
					} else{
						alert('Error Adding category!');
					}

				},
				error: function(xhr, textStatus, errorThrown) {
					console.log('Error! '+textStatus+"="+errorThrown);
				}
			});
			return false;
		});
		

		$("#tailor_portfolio_form").submit(function(event) {
			var name = $("#id_form_port-name").val();

			$.ajax({
				url: '/dashboard/tailor/portfolio/add/ajax/'+name+'/{{ object.id }}/',
				type: 'GET',
				dataType: 'text',
				success: function(data, textStatus, xhr) {
					// $("#id_form1-portfolio").append('<option value="'+data+'">'+name+'</option>');

					// $("#id_form_port-name").val('');
					// myDropzone1.removeAllFiles(true);
					if(data!="0"){
						alert('Portfolio added!');
						window.location.reload();
					} else{
						alert('Error Adding Portfolio!');
					}
				},
				error: function(xhr, textStatus, errorThrown) {
					console.log('Error! '+textStatus+"="+errorThrown);
				}
			});
			return false;
		});


	});

</script>

{% endblock extrascripts %}

ritzley/templates/dashboard/tailor/tailor_delete.html
{% extends 'dashboard/index.html' %}
{% load i18n %}
{% load staticfiles %}

{% block headertext %}
    <span>{{tailor.name}}</span> <span>{% trans "Tailor" %}</span>
{% endblock %}

{% block dashboard_content %}

<form action="" method="post">
{% csrf_token %}
    <p>Are you sure you want to delete "{{ tailor }}"?</p>
    <input type="submit" value="Confirm" />
</form>

{% endblock %}