ritzley/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from oscar.app import application

from django.conf import settings
from django.conf.urls.static import static

from Custom_apps.cart.app import application1

urlpatterns = [
	url(r'^i18n/', include('django.conf.urls.i18n')),
	# url(r'^register/', views.UserRegistration.as_view(), name='UserRegistration'),
	# The Django admin is not officially supported; expect breakage.
	# Nonetheless, it's often useful for debugging.
	url(r'^admin/', include(admin.site.urls)),
	url(r'', include(application.urls)),

	## Custom urls in cart
	url(r'', include(application1.urls)),

	


	# ----------------Custom Urls-----------------------------------
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Custom_apps/dashboard/models.py
from django.db import models
# from oscar.apps.dashboard.models import *
from django.contrib.auth.models import User
from Custom_apps.dashboard.tailor.models import Tailor, TailorCategory

import datetime


class Faq(models.Model):

	description = models.TextField()

	class Meta:
		verbose_name = "Faq"
		verbose_name_plural = "Faqs"

	def __unicode__(self):
		return self.description



class Templatepage(models.Model):
	# TODO: Define fields here
	
	name = models.CharField(max_length=50)

	def __unicode__(self):
		return self.name


class Color(models.Model):

	name = models.CharField(blank=False, null=False,max_length=50)

	def __unicode__(self):
		return self.name


"""
If more stiching category needed to be entered, then use below model for stiching
"""
# class Stiching(models.Model):

# 	title = models.CharField(blank=False, null=False,max_length=50)

# 	def __unicode__(self):
# 		return self.title


class Boutique(models.Model):
	# TODO: Define fields here
	
	name = models.CharField(max_length=50, blank=False, null=False)
	description = models.TextField(blank=True, null=True)
	faq = models.TextField(blank=True, null=True)
	refund_policy = models.TextField(blank=True, null=True)
	terms_conditions = models.TextField(blank=True, null=True)
	header_image = models.ImageField(default="Unknown.jpg",blank=True, null=True)
	logo = models.ImageField(default="Unknown.jpg", blank=True, null=True)
	placeholder_1 = models.ImageField(default="Unknown.jpg", blank=True, null=True, verbose_name='Placeholder 1')
	placeholder_2 = models.ImageField(default="Unknown.jpg", blank=True, null=True, verbose_name='Placeholder 2')
	location = models.CharField(blank=False, null=False, max_length=50)
	featured = models.BooleanField(default=False)
	template = models.ForeignKey(Templatepage, blank=False, null=False, default=False)
	url = models.CharField(max_length=1024, default="ritzley.com", null=False, blank=False)
	fb_url = models.CharField(max_length=1024, default="facebook.com", null=True, blank=True)
	tailor = models.ForeignKey(Tailor, blank=True, null=True)
	active = models.BooleanField(default=True)
	email = models.CharField(max_length = 1024,blank=True)
	
	def __unicode__(self):
		return self.name


# Category for products
class Category(models.Model):

	name = models.CharField(blank=False, null=False, max_length=50)
	def __unicode__(self):
		return self.name


# Product size for product. This is inserted in seperate table because each size has its on stock
class Product_size1(models.Model):
	
	product_size = models.CharField(blank=False, null=False, max_length=50)
	stock = models.IntegerField(blank=False, null=False, default=0)

	def __unicode__(self):
		return "{0} - {1} - {2}".format(self.id, self.product_size, self.stock)

# Images for products are used
class Product_image1(models.Model):

	image = models.ImageField(default="Unknown.jpg")

	def __unicode__(self):
		return self.image.name


# Product model for inserting products 
class Product(models.Model):


	STITCHED = 'Stitched'
	HALF_STITCHED = 'Half-Stitched'
	FULL_STITCHED = 'Non-Stitched'

	STITCHING = (
		(STITCHED, 'Stitched'),
		(HALF_STITCHED, 'Half-Stitched'),
		(FULL_STITCHED, 'Non-Stitched'),
	)

	boutique = models.ForeignKey(Boutique, blank=False, null=False, related_name="boutique", default=True)
	category = models.ForeignKey(Category, blank=False, null=False, default=True)
	name = models.CharField(blank=False, null=False, max_length=50,default="")
	# stock = models.IntegerField(default=0)
	price = models.IntegerField(blank=False, null=False, max_length=50,default=0)
	description = models.TextField(blank=True, null=True, max_length=1000)
	tags = models.CharField(blank=True, null=True, max_length=1000)
	discount = models.IntegerField(default = 0, blank=True, null=True)
	discount_amount = models.IntegerField(default = 0, blank=True, null=True)
	color = models.ForeignKey(Color, blank=False, null=False, default=True)
	# stiching = models.ForeignKey(Stiching, blank=False, null=False, default=True)
	stitching = models.CharField(max_length=50, choices=STITCHING, default=STITCHED)
	added_date = models.DateTimeField('date added', auto_now=True, auto_now_add=True, default=datetime.date.today())
	featured = models.BooleanField(default=False)

	image = models.ManyToManyField(Product_image1, null=True, blank=True)
	size = models.ManyToManyField(Product_size1, null=True, blank=True)

	def __unicode__(self):
		return "{0} - {1} - {2}".format(self.id, self.name, self.stitching)


"""Model for capturing user's favourite boutiques"""
class Boutique_favourite(models.Model):

	user = models.ForeignKey(User, blank=False, null=False, default=True)
	boutique = models.ForeignKey(Boutique, blank=False, null=False, default=True)

	def __unicode__(self):
		return self.boutique.name









	

Custom_apps/dashboard/forms.py
from django import forms
from models import *
from Custom_apps.dashboard.models import *

# Create your forms here

class BoutiqueForm(forms.ModelForm):

    class Meta:
        model = Boutique
        exclude = [],


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ['category', 'name', 'price', 'description', 'tags', 'discount','featured', 'image', 'boutique', 'stitching', ]
        exclude = ['boutique', 'discount_amount', 'added_date,', 'size', 'image', ]


class Product_image_form(forms.ModelForm):

    class Meta:
        model = Product_image1
        exclude = [],



class Product_size_form(forms.ModelForm):

    class Meta:
        model = Product_size1
        exclude = [],


class DocumentForm(forms.Form):
    image = forms.ImageField()

Custom_apps/dashboard/tailor/forms.py
from django import forms
from models import *
from Custom_apps.dashboard.tailor.models import *


class TailorForm(forms.ModelForm):

    class Meta:
        model = Tailor
        exclude = [],


class TailorPortfolioForm(forms.ModelForm):

    class Meta:
        model = TailorPortfolio
        exclude = [],


class TailorCategoryForm(forms.ModelForm):

    class Meta:
        model = TailorCategory
        exclude = [],


class TailorSubCategoryForm(forms.ModelForm):

    class Meta:
        model = TailorSubCategory
        exclude = [],


class TailorPatternsForm(forms.ModelForm):

    class Meta:
        model = TailorPatterns
        exclude = [],

Custom_apps/dashboard/users/forms.py
from django import forms
from django.contrib.auth.models import User


# Create your forms here

class UserForm(forms.Form):
	# TODO: Define form fields here

	first_name = forms.CharField()
	last_name = forms.CharField()
	email = forms.EmailField()
	password = forms.CharField(widget=forms.PasswordInput)


class UserModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password']
        # widgets = {
        #     'password': forms.PasswordInput(),
        # }

Custom_apps/dashboard/boutique/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.views.generic import View, TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from django.core.urlresolvers import reverse_lazy, reverse
from Custom_apps.dashboard.models import Boutique
from django.contrib import messages

from django.forms.formsets import formset_factory, BaseFormSet
from django.forms.models import modelformset_factory

from Custom_apps.dashboard.forms import *
from Custom_apps.dashboard.models import *
from django.core.exceptions import ObjectDoesNotExist



# Create Your views here
# This displays the boutique list
class boutique_list_view(ListView):

	model = Boutique
	context_object_name = "boutiques"
	template_name = "dashboard/boutique/boutique_index.html"

	def get_context_data(self, **kwargs):
		context = super(boutique_list_view, self).get_context_data(**kwargs)
		cate_obj = Category.objects.all()
		context['categorys'] = cate_obj
		return context


# Add Boutiques
class add_boutique_view(TemplateView):

	Form  = BoutiqueForm()
	template_name = "dashboard/boutique/boutique_add.html"

	# renders from this method when entering the url
	def get_context_data(self, **kwargs):

		context = super(add_boutique_view, self).get_context_data(**kwargs)
		context['form'] = self.Form
		context['form_action'] = "/dashboard/boutique/add/"
		return context

	# On button click post method will accessed to save the details and image files into the database
	def post(self, request):

		context = {}
		form = BoutiqueForm(request.POST, request.FILES)
		if form.is_valid():
			form.save()
			messages.success(request, 'Added new boutique')
		else:
			messages.error(request, 'Please fill all fields')
			return HttpResponseRedirect(reverse_lazy('dashboard:add-boutique'))

		context['form'] = self.Form
		return HttpResponseRedirect(reverse_lazy('dashboard:boutique-list'))


# Delete Boutiques
class delete_boutique_view(DeleteView):

	model = Boutique
	context_object_name = "boutique"
	template_name = "dashboard/boutique/boutique_delete.html"
	success_url = reverse_lazy('dashboard:boutique-list')


# Detailed view of Boutiques, This view also adds the product according to boutique
class boutique_detail_view(DetailView):

	model = Boutique
	context_object_name = "boutique"
	template_name = "dashboard/boutique/boutique_details.html"

	def get_context_data(self, **kwargs):

		context = super(boutique_detail_view, self).get_context_data(**kwargs)
		bout_obj = self.get_object()
		pro_obj = Product.objects.filter(boutique=bout_obj)
		fav_bout_obj = Boutique_favourite.objects.filter(boutique=bout_obj)
		print fav_bout_obj

		context['Products'] = pro_obj
		context['Fav_boutique'] = fav_bout_obj

		return context


# class boutique_detail_view(DetailView):

# 	model = Boutique
# 	product_form_class = ProductForm
# 	image_form_class = Product_image_form
# 	context_object_name = "boutique"
# 	template_name = "dashboard/boutique/boutique_details.html"

# 	def get_context_data(self, **kwargs):

# 		context = super(boutique_detail_view, self).get_context_data(**kwargs)
# 		context['form_product'] = self.product_form_class
# 		context['form_image'] = self.image_form_class
# 		return context

# 	def post(self, request, **kwargs):

# 		bout_id = kwargs['pk']
# 		bout_obj = Boutique.objects.get(id=bout_id)
# 		form_product = ProductForm(request.POST).save(commit=False)
# 		form_product.boutique = bout_obj
# 		discount = form_product.discount
		
# 		"""Checking whether there is any discount applied to this product 
# 		and if there is discount applied, discount amount is calculated and saved"""
# 		if discount != 0:
# 			price = form_product.price
# 			discount_amount = price - (price*discount/100)
# 			form_product.discount_amount = discount_amount

# 		form_product.save()
# 		form_image = Product_image_form(request.POST,request.FILES)
# 		if form_image.is_valid():
# 			form_image = form_image.save()
# 			form_product.image.add(form_image)
# 		return HttpResponseRedirect(reverse_lazy('dashboard:product-list'))


# Edit details view of Boutiques
class boutique_edit_view(UpdateView):

	model = Boutique
	template_name = "dashboard/boutique/boutique_edit.html"
	success_url = reverse_lazy('dashboard:boutique-list')

	def post(self, request, **kwargs):

		context = super(boutique_edit_view, self).post(request,**kwargs)
		messages.success(request, "Updated boutique")
		return context



class delete_size(TemplateView):
	template_name = "index.html"

	def get(self, request, **kwargs):

		bout_id = kwargs["pk"]

		if bout_id:
			try:
				size = Product_size1.objects.get(id=bout_id)
				size.delete()
				return HttpResponse("1") 
			except Exception, e:
				return HttpResponse("-1")
		else:
			return HttpResponse("-2") 



class delete_image(TemplateView):
	template_name = "index.html"

	def get(self, request, **kwargs):

		bout_id = kwargs["pk"]
		
		if bout_id:
			try:
				size = Product_image1.objects.get(id=bout_id)
				size.delete()
				messages.success(request, "Item deleted")
			except Exception, e:
				messages.errors(request, "Item does not exist")
		else:
			messages.errors(request, "Missing args")

		return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))





def upload(request):
	c={}

	if request.method == 'POST':
		
		ims = request.session['im']

		image = request.FILES.get('file', 'unknown.jpg')
		form = Product_image_form(request.POST, request.FILES)
		im = Product_image1(image=image)
		im.save()

		ims.append(im.id)
		request.session['im'] = ims	
		print ims
	else:
		return HttpResponse('Not OK')

	return HttpResponse('OK')



# This view edit's the products
class product_add(TemplateView):
	
	template_name = "dashboard/boutique/product_add.html"
	success_url = reverse_lazy('dashboard:boutique-list')


	def post(self, request, *args, **kwargs):

		QuoteItemFormFormset = formset_factory(Product_size_form)

		bout_id = kwargs["bout_id"]
		boutique = Boutique.objects.get(id=bout_id)

		product_form = ProductForm(request.POST)
		if product_form.is_valid():
			obj = product_form.save(commit=False)
		else:
			messages.error(request, "Please Fill all fields!")
			return self.get(self, request, *args, **kwargs)


		obj.boutique = boutique
		discount = obj.discount
		
# 		"""Checking whether there is any discount applied to this product 
# 		and if there is discount applied, discount amount is calculated and saved"""
		if discount != 0:
			price = obj.price
			discount_amount = price - (price*discount/100)
			obj.discount_amount = discount_amount

		obj.save()

		product_image_form = Product_image_form(request.POST, request.FILES)
		product_image_form.save()

		product_size_formset = QuoteItemFormFormset(request.POST)

		print "formset=",product_size_formset

		if product_size_formset.is_valid():
			for form in product_size_formset.forms:
				obj = form.save()
				obj.save()
				product_form.instance.size.add(obj)
				product_form.save()
		else:
			print "Invalid formset"

		images = self.request.session['im']
		print images
		for img in images:
			product_form.instance.image.add(img)

		request.session['im'] = []

		messages.success(request, "New product has been added")

		return redirect(self.success_url)


	def get_context_data(self, **kwargs):

		self.request.session['im'] = []

		context = super(product_add, self).get_context_data(**kwargs)

		product_form = ProductForm()
		product_image_form = Product_image_form()
		product_size_form = Product_size_form()
		QuoteItemFormFormset = formset_factory(Product_size_form)

		context['form'] = product_form
		context['image_form'] = product_image_form
		context['size_form'] = QuoteItemFormFormset

		return context



# This view edit's the products
class product_edit(TemplateView):
	
	# model = Product
	# fields = ['category', 'name', 'price', 'description', 'tags', 'discount','image','featured']
	template_name = "dashboard/boutique/product_edit.html"
	success_url = reverse_lazy('dashboard:boutique-list')


	def post(self, request, *args, **kwargs):

		product_id = kwargs['pk']
		product = Product.objects.get(id=product_id)

		product_form = ProductForm(request.POST, instance=product)
		obj = product_form.save(commit=False)

		discount = obj.discount
		
# 		"""Checking whether there is any discount applied to this product 
# 		and if there is discount applied, discount amount is calculated and saved"""
		if discount != 0:
			price = obj.price
			discount_amount = price - (price*discount/100)
			obj.discount_amount = discount_amount

		obj.save()

		product_image_form = Product_image_form(request.POST, request.FILES)
		product_image_form.save()

		sizes = product.size.all()

		QuoteItemFormFormset = modelformset_factory(Product_size1, extra=0)
		product_size_formset = QuoteItemFormFormset(request.POST, queryset=sizes)


		if product_size_formset.is_valid():
			for form in product_size_formset.forms:
				obj = form.save(commit=False)
				obj.save()
				product_form.instance.size.add(obj)

		else:
			print "Invalid formset"

		images = self.request.session['im']
		print images
		for img in images:
			product_form.instance.image.add(img)

		request.session['im'] = []

		messages.success(request, "Product has been saved")

		return redirect(self.success_url)



	def get_context_data(self, **kwargs):

		self.request.session['im'] = []

		context = super(product_edit, self).get_context_data(**kwargs)

		product_id = kwargs['pk']
		product = Product.objects.get(id=product_id)

		product_form = ProductForm(instance=product)
		product_image_form = Product_image_form()

		# QuoteItemFormFormset = formset_factory(Product_size_form, extra=0)
		# QuoteItemFormFormset = modelformset_factory(Product_size1)
		QuoteItemFormFormset = modelformset_factory(Product_size1, extra=0)

		sizes = []
		for i in product.size.all():
			c = {}

ritzley/templates/dashboard/boutique/boutique_add.html
{% extends 'dashboard/index.html' %}
{% load i18n %}
{% load staticfiles %}

{% block headertext %}
	{% trans "Boutique" %}
{% endblock %}

{% block dashboard_content %}
	<form action="" method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{form.as_p}}
	<input type="submit" value="Submit" class="btn btn-primary">
	</form>
	<a href="/dashboard/"><input type="button" value="Home" class="btn btn-primary"></a>

{% endblock %}

ritzley/templates/dashboard/boutique/boutique_delete.html
{% extends 'dashboard/index.html' %}
{% load i18n %}
{% load staticfiles %}

{% block headertext %}
    <span>{{boutique.name}}</span> <span>{% trans "Boutique" %}</span>
{% endblock %}

{% block dashboard_content %}

<form action="" method="post">
{% csrf_token %}
    <p>Are you sure you want to delete "{{ boutique }}"?</p>
    <input type="submit" value="Confirm" />
</form>

{% endblock %}

ritzley/templates/dashboard/boutique/boutique_edit.html
{% extends 'dashboard/index.html' %}
{% load i18n %}
{% load staticfiles %}

{% block headertext %}
    <span>{{boutique.name}}</span> <span>{% trans "Boutique" %}</span>
{% endblock %}

{% block dashboard_content %}

<form action="" method="post" enctype="multipart/form-data" >
	{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
{% endblock %}

ritzley/templates/dashboard/boutique/boutique_template_delete.html
{% extends 'dashboard/index.html' %}
{% load i18n %}
{% load staticfiles %}

{% block headertext %}
    <span>{% trans "Boutique Template" %}</span>
{% endblock %}

{% block dashboard_content %}

<form action="" method="post">
{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

{% endblock %}

ritzley/templates/dashboard/boutique/product_delete.html
{% extends 'dashboard/index.html' %}
{% load i18n %}
{% load staticfiles %}

{% block headertext %}
    <span>{{product.name}}</span>
{% endblock %}

{% block dashboard_content %}

<form action="" method="post">
{% csrf_token %}
    <p>Are you sure you want to delete "{{ product }}"?</p>
    <input type="submit" value="Confirm" />
</form>

{% endblock %}

ritzley/templates/dashboard/boutique/product_edit.html
{% extends 'dashboard/index.html' %}
{% load i18n %}
{% load staticfiles %}
{% load thumbnail %}

{% block dashboard_content %}

<div class="form-group col-md-6">
  <label>Upload Images</label>
  <form action="/dashboard/boutique/upload/" class="dropzone" id="my-awesome-dropzone" style="min-height: 200px; max-width: 500px;" method="POST">
    {% csrf_token %}
    <div class="fallback">
      <input name="file" type="file" multiple="" accept="image/*"/>
    </div>
  </form>
</div>

{% if images %}
<div style="min-height: 200px; max-width: 600px;">

  {% for img in images %}
  <div class="img_single">
    <div>
      {% with img.image as image %}
      {% thumbnail image "80x100" format="PNG" crop="top" as image2 %}
      <img src="{{ image2.url }}" width="100px">
      {% endthumbnail %}

      {% endwith %}

    </div>
    <div><a href="/dashboard/boutique/delete_image/{{ img.id }}">Delete</a></div>
  </div>
  {% endfor %}

</div>

<div style="clear:both"></div>
<br />
<br />
<br />
{% endif %}

<form action="" method="post" enctype="multipart/form-data" class="col-md-8" >{% csrf_token %}
  {{ form.as_p }}

  {{ size_form.management_form }}


  <table class="table responsive table-striped table-bordered" style="max-width:300px;" id="id_stock_table">
   <caption>
    <h3 class="pull-left"> <i class="icon-sitemap icon-large"></i>Add Sizes for Product</h3>
  </caption>

  <tr>
    <th>Size</th>
    <th>Stock</th>
    <!-- <th>Add</th> -->
    <th>Delete</th>
  </tr>

  {% for form in size_form.forms %}
  <tr class="item">
    <td>{{ form.visible_fields.0 }} <p>{{ form.visible_fields.0.error }}</p></td>
    <td>{{ form.visible_fields.1 }} <p>{{ form.visible_fields.1.error }}</p></td>
    <!-- <td>{{ form.id }}<div style="color:green; cursor:pointer;" id="add">Add</div></td> -->
    <td>{{ form.id }}<div style="color:red; cursor:pointer;" class="delete" id="{{ form.id.value }}">Delete</div></td>
  </tr>

  {% endfor %}
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td><div style="color:green; cursor:pointer;" id="add">Add</div></td>
  </tr>

</table>


<input type="submit" value="Save" />
</form>


{% endblock %}

{% block extrascripts %}
<!-- DROPZONE -->
<script type="text/javascript" src={% static "js/dropzone/dropzone.min.js" %}></script>

<script type="text/javascript">
  $(document).ready(function() {

    $("#id_discount").siblings('label').text("Discount: (Enter as precentage)");

  });
</script>

<script type="text/javascript">

  $(document).ready(function () {
    // Code adapted from http://djangosnippets.org/snippets/1389/  
    function updateElementIndex(el, prefix, ndx) {
      var id_regex = new RegExp('(' + prefix + '-\\d+-)');
      var replacement = prefix + '-' + ndx + '-';
      if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex,
        replacement));
        if (el.id) el.id = el.id.replace(id_regex, replacement);
      if (el.name) el.name = el.name.replace(id_regex, replacement);
    }

    function deleteForm(btn, prefix) {
      var formCount = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
      if (formCount > 1) {
            // Delete the item/form
            $(btn).parents('.item').remove();
            var forms = $('.item'); // Get all the forms  
            // Update the total number of forms (1 less than before)
            $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
            var i = 0;
            // Go through the forms and set their indices, names and IDs
            for (formCount = forms.length; i < formCount; i++) {
              $(forms.get(i)).children().children().each(function () {
                if ($(this).attr('type') == 'text') updateElementIndex(this, prefix, i);
              });
            }
        } // End if
        else {
          alert("You have to atleast add 1 item!");
        }
        return false;
      }

      function addForm(btn, prefix) {
       var formCount = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
        // You can only submit a maximum of 10 todo items 
        if (formCount < 10) {
            // Clone a form (without event handlers) from the first form
            var row = $(".item:first").clone(false).get(0);
            // Insert it after the last form
            $(row).removeAttr('id').hide().insertAfter(".item:last").slideDown(300);

            // Remove the bits we don't want in the new row/form
            // e.g. error messages
            $(".errorlist", row).remove();
            $(row).children().removeClass("error");

            // Relabel or rename all the relevant bits
            $(row).children().children().each(function () {
              updateElementIndex(this, prefix, formCount);
              $(this).val("");
            });

            // Add an event handler for the delete item/form link 
            $(row).find(".delete").click(function () {
              return deleteForm(this, prefix);
            });
            // Update the total form count
            $("#id_" + prefix + "-TOTAL_FORMS").val(formCount + 1);
        } // End if
        else {
          alert("Sorry, you can only enter a maximum of ten items.");
        }
        return false;
      }
    // Register the click event handlers
    $("#add").click(function () {
      return addForm(this, "form");
    });

    $(".delete").click(function () {

      var val = $(this).attr('id');
      var status="0"; 
      var me = this;

      if(val != "None"){
        $.ajax({
          url: '/dashboard/boutique/delete_size/'+val,
          type: 'GET',
          dataType: '',
          success: function(data, textStatus, xhr) {
                //called when successful
                // return deleteForm(this, "form");
                status=data;

                if(status == "1"){
                  return deleteForm(me, "form");
                } else if(status == "-1"){
                  alert("Error Deleting Size");
                } else if(status == "-2"){
                  alert("Item Does not Exist");
                } else if(status == "0"){
                  alert("Error Deleting Size");
                }

              },
              error: function(xhr, textStatus, errorThrown) {
            //called when there is an error
            alert("Error: "+textStatus);
          }
        });

      } else {
        alert("Row could not be removed!");
      }


    });
});
</script>

{% endblock %}


{% block extrastyles %}

<!-- DROPZONE -->
<link rel="stylesheet" type="text/css" href={% static "js/dropzone/dropzone.min.css" %} />

<style type="text/css">
  .img_single{
    float: left;
  }
</style>

{% endblock %}

ritzley/templates/dashboard/boutique/product_image_add.html
{% extends 'dashboard/index.html' %}
{% load i18n %}
{% load staticfiles %}

{% block dashboard_content %}

<form action="" method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Update" />
</form>
{% endblock %}

ritzley/templates/dashboard/boutique/product_list.html
{% extends 'dashboard/index.html' %}
{% load i18n %}
{% load staticfiles %}

{% block dashboard_content %}
    {% for product in products %}
    <a href="/dashboard/boutique/details_product{{product.id}}">
        <span>{{product}}</span>
    </a>
    <a href="/dashboard/boutique/edit_product/{{product.id}}"><input type="button" value="Edit" class="btn btn-primary"></a>
    <a href="/dashboard/boutique/delete_product/{{product.id}}"><input type="button" value="Delete" class="btn btn-primary"></a>
    <hr>
    {% endfor %}

    <a href="/dashboard/boutique/add/"><input type="button" value="add" class="btn btn-primary"></a>
{% endblock %}